package com.sasaarsenovic.customwidgetslibrary.calendar;

public enum IndicatorShapes {
    CIRCLE,
    SQUARE,
    RECTANGLE,
    STAR,
    TRIANGLE,
    INVERSE_TRIANGLE,
    HEXAGON,
    OCTAGON,
    CIRCLE_WITH_SHADOW,
    SQUARE_WITH_SHADOW,
    RECTANGLE_WITH_SHADOW,
    STAR_WITH_SHADOW,
    TRIANGLE_WITH_SHADOW,
    INVERSE_TRIANGLE_WITH_SHADOW,
    HEXAGON_WITH_SHADOW,
    OCTAGON_WITH_SHADOW,
    UNDERLINED
}
